#!/usr/bin/env sh
# generated from catkin/python/catkin/environment_cache.py

# based on a snapshot of the environment before and after calling the setup script
# it emulates the modifications of the setup script without recurring computations

# new environment variables

# modified environment variables
export CMAKE_PREFIX_PATH="/home/tyh/DB_plan_Project/src/armadillo-9.870.2/devel:$CMAKE_PREFIX_PATH"
export LD_LIBRARY_PATH='/home/tyh/DB_plan_Project/src/armadillo-9.870.2/devel/lib:/home/tyh/.mujoco/mujoco210/bin:/home/tyh/gurobi1101/linux64/lib:/home/tyh/.mujoco/mujoco210/bin:/home/tyh/.mujoco/mujoco210/bin:/home/tyh/gurobi1101/linux64/lib:/home/tyh/gurobi1101/linux64/lib:/home/tyh/.mujoco/mujoco210/bin:/home/tyh/.mujoco/mujoco210/bin:/home/tyh/gurobi1101/linux64/lib:/home/tyh/.mujoco/mujoco210/bin:/home/tyh/.mujoco/mujoco210/bin:/home/tyh/gurobi1101/linux64/lib:/home/tyh/gurobi1101/linux64/lib:/home/tyh/gurobi1101/linux64/lib:/home/tyh/.mujoco/mujoco210/bin:/home/tyh/.mujoco/mujoco210/bin:/home/tyh/gurobi1101/linux64/lib:/home/tyh/.mujoco/mujoco210/bin:/home/tyh/.mujoco/mujoco210/bin:/home/tyh/gurobi1101/linux64/lib:/home/tyh/gurobi1101/linux64/lib:/home/tyh/.mujoco/mujoco210/bin:/home/tyh/.mujoco/mujoco210/bin:/home/tyh/gurobi1101/linux64/lib:/home/tyh/.mujoco/mujoco210/bin:/home/tyh/.mujoco/mujoco210/bin:/home/tyh/gurobi1101/linux64/lib:/home/tyh/gurobi1101/linux64/lib:/home/tyh/gurobi1101/linux64/lib:/home/tyh/gurobi1101/linux64/lib:/home/tyh/.mujoco/mujoco210/bin:/opt/ros/noetic/lib:/opt/ros/noetic/lib/x86_64-linux-gnu:/home/tyh/.mujoco/mujoco210/bin:/home/tyh/gurobi1101/linux64/lib:/home/tyh/.mujoco/mujoco210/bin:/home/tyh/.mujoco/mujoco210/bin:/home/tyh/gurobi1101/linux64/lib:/home/tyh/gurobi1101/linux64/lib:/home/tyh/.mujoco/mujoco210/bin:/home/tyh/.mujoco/mujoco210/bin:/home/tyh/gurobi1101/linux64/lib:/home/tyh/.mujoco/mujoco210/bin:/home/tyh/.mujoco/mujoco210/bin:/home/tyh/gurobi1101/linux64/lib:/home/tyh/gurobi1101/linux64/lib:/home/tyh/gurobi1101/linux64/lib:/home/tyh/.mujoco/mujoco210/bin:/home/tyh/.mujoco/mujoco210/bin:/home/tyh/gurobi1101/linux64/lib:/home/tyh/.mujoco/mujoco210/bin:/home/tyh/.mujoco/mujoco210/bin:/home/tyh/gurobi1101/linux64/lib:/home/tyh/gurobi1101/linux64/lib:/home/tyh/.mujoco/mujoco210/bin:/home/tyh/.mujoco/mujoco210/bin:/home/tyh/gurobi1101/linux64/lib:/home/tyh/.mujoco/mujoco210/bin:/home/tyh/.mujoco/mujoco210/bin:/home/tyh/me5400a_ws2/devel/lib:/home/tyh/gurobi1101/linux64/lib:/home/tyh/gurobi1101/linux64/lib:/home/tyh/gurobi1101/linux64/lib:/home/tyh/gurobi1101/linux64/lib:/home/tyh/gurobi1101/linux64/lib'
export PATH='/opt/ros/noetic/bin:/home/tyh/CUTE/cutest/bin:/home/tyh/CUTE/sifdecode/bin:/home/tyh/CUTE/cutest/bin:/home/tyh/CUTE/sifdecode/bin:/home/tyh/anaconda3/envs/DBProject_env/bin:/home/tyh/CUTE/cutest/bin:/home/tyh/CUTE/sifdecode/bin:/home/tyh/CUTE/cutest/bin:/home/tyh/CUTE/sifdecode/bin:/opt/gcc-arm-none-eabi-9-2020-q2-update/bin:/home/tyh/.local/bin:/home/tyh/CUTE/cutest/bin:/home/tyh/CUTE/sifdecode/bin:/home/tyh/anaconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/wsl/lib:/mnt/c/Python312/Scripts:/mnt/c/Python312:/mnt/c/Program Files/CMake/bin:/mnt/c/Windows/System32:/mnt/c/Users/tyh/AppData/Local/Programs/Python/Python38/Scripts:/mnt/c/Program Files/Git/cmd:/mnt/c/mingw64/mingw64/bin:/mnt/c/Program Files/Microsoft SQL Server/150/Tools/Binn:/mnt/c/msys64/usr/bin:/mnt/c/Program Files/Docker/Docker/resources/bin:/mnt/c/Users/tyh/miniconda3/Scripts:/mnt/c/Users/tyh/miniconda3:/mnt/c/Program Files/nodejs:/mnt/c/ProgramData/chocolatey/bin:/mnt/c/Users/tyh/miniconda3/envs/soft:/mnt/c/Users/tyh/miniconda3/envs/soft/DLLs:/mnt/c/Users/tyh/miniconda3/envs/soft/Lib:/mnt/c/Users/tyh/SOFA_v23.06.00_Win64/SOFA_v23.06.00_Win64/bin:/mnt/c/Users/tyh/scoop/shims:/mnt/c/Users/tyh/AppData/Local/Programs/Python/Python38:/mnt/c/Users/tyh/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/tyh/AppData/Local/Programs/Microsoft VS Code/bin:/mnt/c/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/bin:/mnt/c/opencv47/opencv/build/x64/vc14/bin:/mnt/c/Program Files/JetBrains/PyCharm 2023.2/bin:/mnt/c/Users/tyh/AppData/Roaming/npm:/snap/bin:/home/tyh/gurobi1101/linux64/bin:/home/tyh/SOFA_v23.06.00_Linux/bin:/home/tyh/gurobi1101/linux64/bin:/home/tyh/gurobi1101/linux64/bin:/home/tyh/gurobi1101/linux64/bin:/home/tyh/gurobi1101/linux64/bin'
export PKG_CONFIG_PATH="/home/tyh/DB_plan_Project/src/armadillo-9.870.2/devel/lib/pkgconfig:$PKG_CONFIG_PATH"
export PYTHONPATH="/home/tyh/DB_plan_Project/src/armadillo-9.870.2/devel/lib/python3/dist-packages:$PYTHONPATH"
export ROSLISP_PACKAGE_DIRECTORIES="/home/tyh/DB_plan_Project/src/armadillo-9.870.2/devel/share/common-lisp:$ROSLISP_PACKAGE_DIRECTORIES"
export ROS_PACKAGE_PATH="/home/tyh/DB_plan_Project/src:$ROS_PACKAGE_PATH"